spring:
  datasource:
    url: jdbc:mysql://localhost:3306/feed
    username: root
    password: root1123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true